src/main/java/com/parasoft/parabank/domain/Customer.java
package com.parasoft.parabank.domain;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.parasoft.parabank.util.Util;

/**
 * Domain object representing a bank customer
 */

@XmlRootElement(name="customer")
@XmlType(propOrder={"id", "firstName", "lastName", "address", "phoneNumber", "ssn"})

public class Customer {
    private int id;
    private String firstName;
    private String lastName;
    private Address address;
    private String phoneNumber;
    private String ssn;
    private String username;
    private String password;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @XmlTransient
    @JsonIgnore
    public String getFullName() {
        return firstName + " " + lastName;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getSsn() {
        return ssn;
    }

    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    @XmlTransient
    @JsonIgnore
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @XmlTransient
    @JsonIgnore
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + id;
        result = prime * result + (firstName == null ? 0 : firstName.hashCode());
        result = prime * result + (lastName == null ? 0 : lastName.hashCode());
        result = prime * result + (address == null ? 0 : address.hashCode());
        result = prime * result + (phoneNumber == null ? 0 : phoneNumber.hashCode());
        result = prime * result + (ssn == null ? 0 : ssn.hashCode());
        result = prime * result + (password == null ? 0 : password.hashCode());
        result = prime * result + (username == null ? 0 : username.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Customer)) {
            return false;
        }
        Customer other = (Customer) obj;
        return id == other.id &&
            Util.equals(firstName, other.firstName) &&
            Util.equals(lastName, other.lastName) &&
            Util.equals(address, other.address) &&
            Util.equals(phoneNumber, other.phoneNumber) &&
            Util.equals(ssn, other.ssn) &&
            Util.equals(username, other.username) &&
            Util.equals(password, other.password);
    }

    @Override
    public String toString() {
        return "Customer [id=" + id + ", firstName=" + firstName
                + ", lastName=" + lastName + ", address=" + address
                + ", phoneNumber=" + phoneNumber + ", ssn=" + ssn
                + ", username=" + username + ", password=" + password + "]";
    }
}

src/main/webapp/WEB-INF/jsp/include/buttons.jsp
<%@ include file="include.jsp" %>

<ul class="button">
  <li class="home"><a href="<c:url value="/index.htm"/>">home</a></li>
  <li class="aboutus"><a href="<c:url value="about.htm"/>">about</a></li>
  <li class="contact"><a href="<c:url value="contact.htm"/>">contact</a></li>
</ul>

src/main/webapp/WEB-INF/jsp/include/footerPanel.jsp
<%@ include file="include.jsp" %>

<div id="footermainPanel">
  <div id="footerPanel">
    <ul>
      <li><a href="<c:url value="/index.htm"/>"><fmt:message key="home"/></a>| </li>
      <li><a href="<c:url value="about.htm"/>"><fmt:message key="about.us"/></a>| </li>
      <li><a href="<c:url value="services.htm"/>"><fmt:message key="services"/></a>| </li>
      <li><a href="http://www.parasoft.com/jsp/products.jsp"><fmt:message key="products"/></a>| </li>
      <li><a href="http://www.parasoft.com/jsp/pr/contacts.jsp"><fmt:message key="locations"/></a>| </li>
      <li><a href="http://forums.parasoft.com/"><fmt:message key="forum"/></a>| </li>
      <li><a href="<c:url value="/sitemap.htm"/>"><fmt:message key="site.map"/></a>| </li>
      <li><a href="<c:url value="contact.htm"/>"><fmt:message key="contact.us"/></a></li>
    </ul>
    <p class="copyright">&copy; Parasoft. All rights reserved.</p>
    <ul class="visit">
      <li><fmt:message key="visit.us"/>:</li>
      <li><a href="http://www.parasoft.com/" target="_blank">www.parasoft.com</a></li>
    </ul>
  </div>
</div>

src/main/webapp/WEB-INF/jsp/include/headerPanel.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="topPanel.jsp"/>
<div id="headerPanel" style="background: url(<c:url value="/images/header-main.jpg"/>) 0 0 no-repeat;">
  <jsp:include page="leftmenu.jsp"/>
  <jsp:include page="buttons.jsp"/>
</div>

src/main/webapp/WEB-INF/jsp/include/headerPanelCustomer.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="topPanel.jsp"/>
<div id="headerPanel" style="background: url(<c:url value="/images/header-customer.jpg"/>) 0 0 no-repeat;">
  <jsp:include page="leftmenu.jsp"/>
  <jsp:include page="buttons.jsp"/>
</div>

src/main/webapp/WEB-INF/jsp/include/include.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

src/main/webapp/WEB-INF/jsp/include/leftmenu.jsp
<%@ include file="include.jsp" %>

<ul class="leftmenu">
  <li class="Solutions"><fmt:message key="solutions"/></li>
  <li><a href="<c:url value="about.htm"/>"><fmt:message key="about.us"/></a></li>
  <li><a href="<c:url value="services.htm"/>"><fmt:message key="services"/></a></li>
  <li><a href="http://www.parasoft.com/jsp/products.jsp"><fmt:message key="products"/></a></li>
  <li><a href="http://www.parasoft.com/jsp/pr/contacts.jsp"><fmt:message key="locations"/></a></li>
  <li><a href="<c:url value="admin.htm"/>"><fmt:message key="admin.page"/></a></li>
  
</ul>

src/main/webapp/WEB-INF/jsp/include/loginPanel.jsp
<%@ include file="include.jsp" %>

<h2><fmt:message key="customer.login"/></h2>
<div id="loginPanel">
  <form name="login" action="<c:url value="/login.htm"/>" method="POST">
    <c:if test="${!empty loginForwardAction}">
        <input type="hidden" name="forwardAction" value="<c:url value="${loginForwardAction}"/>"/>
    </c:if>
    <p><b><fmt:message key="username"/></b></p>
    <div class="login"><input type="text" class="input" name="username"/></div>
    <p><b><fmt:message key="password"/></b></p>
    <div class="login"><input type="password" class="input" name="password"/></div>
    <div class="login"><input type="submit" class="button" value="Log In"/></div>
  </form>
  <p><a href="<c:url value="lookup.htm"/>"><fmt:message key="forgot.login.info"/></a></p>
  <p><a href="<c:url value="register.htm"/>"><fmt:message key="register"/></a></p>
</div>

src/main/webapp/WEB-INF/jsp/include/navPanel.jsp
<%@ include file="include.jsp" %>

<p class="smallText"><b><fmt:message key="welcome"/></b> ${userSession.customer.fullName}</p>

<h2><fmt:message key="account.services"/></h2>
<jsp:include page="navmenu.jsp"/>

src/main/webapp/WEB-INF/jsp/include/navmenu.jsp
<%@ include file="include.jsp" %>

<ul>
  <li><a href="<c:url value="/openaccount.htm"/>"><fmt:message key="open.new.account"/></a></li>
  <li><a href="<c:url value="/overview.htm"/>"><fmt:message key="accounts.overview"/></a></li>
  <li><a href="<c:url value="/transfer.htm"/>"><fmt:message key="transfer.funds"/></a></li>
  <li><a href="<c:url value="/billpay.htm"/>"><fmt:message key="bill.pay"/></a></li>
  <li><a href="<c:url value="/findtrans.htm"/>"><fmt:message key="find.transactions"/></a></li>
  <li><a href="<c:url value="/updateprofile.htm"/>"><fmt:message key="update.contact.info"/></a></li>
  <li><a href="<c:url value="/requestloan.htm"/>"><fmt:message key="request.loan"/></a></li>
  <li><a href="<c:url value="/logout.htm"/>"><fmt:message key="logout"/></a></li>
</ul>

src/main/webapp/WEB-INF/jsp/include/topPanel.jsp
<%@ include file="include.jsp" %>

<div id="topPanel">
  <a href="<c:url value="/admin.htm"/>"><img src="<c:url value="/images/clear.gif"/>" width="56" height="42" border="0" class="admin"/></a>
  <a href="<c:url value="/index.htm"/>"><img src="<c:url value="/images/logo.gif"/>" alt="ParaBank" width="136" height="31" border="0" class="logo" title="ParaBank"/></a>
  <p class="caption"><fmt:message key="slogan"/></p>
</div>